Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов: Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [33]:
import numpy as np

In [34]:
n1=8
n2=9
n3=11
n=n1+n2+n3
print(n)

28


Всего три группы:

In [35]:
k=3

рост среди взрослых футболистов.
найдем средний рост для футболистов:

In [36]:
y1=np.array([173, 175, 180, 178, 177, 185, 183, 182],dtype=np.int32)
print(y1)
y1_mean=np.mean(y1)
print(y1_mean)

[173 175 180 178 177 185 183 182]
179.125


рост среди взрослых Хоккеисттв.
найдем средний рост для Хоккеистов:

In [37]:
y2=np.array([177, 179, 180, 188, 177, 172, 171, 184, 180],dtype=np.int32)
print(y2)
y2_mean=np.mean(y2)
print(y2_mean)

[177 179 180 188 177 172 171 184 180]
178.66666666666666


рост среди взрослых Штангистов.
найдем средний рост для Штангистов:

In [38]:
y3=np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170],dtype=np.int32)
print(y3)
y3_mean=np.mean(y3)
print(y3_mean)

[172 173 169 177 166 180 178 177 172 166 170]
172.72727272727272


Видно, что средние рост разнятся. Установим, что это отличие статистически значимо. Для этого сначала соберем

все значения ростов в один массив:

In [39]:
y_all=np.concatenate([y1,y2,y3])
y_all

array([173, 175, 180, 178, 177, 185, 183, 182, 177, 179, 180, 188, 177,
       172, 171, 184, 180, 172, 173, 169, 177, 166, 180, 178, 177, 172,
       166, 170])

Найдем среднее рост по всем значениям:

In [40]:
y_mean=np.mean(y_all)
print(y_mean)

176.46428571428572


Найдем $S^2$ — сумму квадратов отклонений наблюдений от общего среднего:

In [41]:
s2=np.sum((y_all-y_mean)**2)
s2

830.9642857142854

Найдем $S^2_F$ - сумму квадратов отклонений средних групповых значений от общего среднего:

In [42]:
s2_f = ((y1_mean - y_mean)**2) * n1 + ((y2_mean - y_mean)**2) * n2 + ((y3_mean - y_mean)**2) * n3
s2_f

253.9074675324678

Найдем $S^2_{ост}$ — остаточную сумму квадратов отклонений:

In [43]:
s2_residual = np.sum((y1 - y1_mean)**2) + np.sum((y2 - y2_mean)**2) + np.sum((y3 - y3_mean)**2)
s2_residual

577.0568181818182

Удостоверимся, что соблюдается равенство:

In [44]:
print(s2)
print(s2_f + s2_residual)

830.9642857142854
830.964285714286


Найдем общую дисперсию:

In [45]:
sigma2_general = s2 / (n - 1)
sigma2_general

30.776455026455015

Найдем факторную дисперсию:

In [46]:
sigma2_f = s2_f / (k - 1)
sigma2_f

126.9537337662339

Найдем остаточную дисперсию:

In [47]:
sigma2_residual = s2_residual / (n - k)
sigma2_residual

23.08227272727273

Вычислим $F_H$:

In [48]:
F_h = sigma2_f / sigma2_residual
F_h

5.500053450812598

$𝐹_𝐻 = 5,5000




  Найдем значение $F_{крит}$ в таблице критических точек распределения Фишера-Снедекора для заданного уровня значимости $\alpha = 0.05$ и двух степеней свободы:

$df_{межд} = k - 1 = 3 - 1 = 2$ и $df_{внутр} = n - k = 20 - 3 = 17$.

Для данных значений $F_{крит} = 3.59$. Так как $F_H > F_{крит}$, отвергнута гипотеза Н0, различие средних ростов в трех группах статистически значимо. то есть выборки имеют разные средние значения.